"""Build the static, server-free web app (runs Python in the browser via Pyodide).

    python scripts/build_web.py

Output: site/index.html (+ worker .js). Upload `site/` to any static host, e.g. GitHub Pages.
The engine, scenarios and data files are bundled into one script because the browser cannot
import the local package.
"""
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD, SITE = ROOT / "build", ROOT / "site"
DATA_FILES = ["baseline_all_india_fy2021.csv", "sources.csv", "anchors_fy2025.csv",
              "state_anchors_fy2025.csv"]


def strip_package_imports(src):
    return "\n".join(l for l in src.splitlines() if not re.match(r"\s*from \.(model|scenarios|io) import", l))


def main():
    parts = ["# Auto-generated by scripts/build_web.py. Edit the source files, not this file."]
    for mod in ["model", "scenarios", "io"]:
        parts.append(strip_package_imports((ROOT / "discom_sim" / f"{mod}.py").read_text()))
    embedded = {n: (ROOT / "data" / n).read_text() for n in DATA_FILES}
    parts.append(f"EMBEDDED_DATA = {embedded!r}")
    app = (ROOT / "app" / "app.py").read_text()
    app = re.sub(r"# --- local imports.*?# --- end local imports ---", "", app, flags=re.S)
    parts.append(app)

    BUILD.mkdir(exist_ok=True)
    bundle = BUILD / "discom_finance_simulator.py"
    bundle.write_text("\n\n".join(parts))

    if SITE.exists():
        shutil.rmtree(SITE)
    subprocess.run(["panel", "convert", str(bundle), "--to", "pyodide-worker", "--out", str(SITE),
                    "--requirements", "pandas", "--title", "DISCOM Finance Simulator"], check=True)
    (SITE / "discom_finance_simulator.html").rename(SITE / "index.html")
    (SITE / ".nojekyll").touch()
    print(f"Built {SITE / 'index.html'}")


if __name__ == "__main__":
    main()
